// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlumGuide.Exercises.PlutoRover.DataAccess;

#nullable disable

namespace PlumGuide.Exercises.PlutoRover.DataAccess.Migrations
{
    [DbContext(typeof(PlutoRoverDbContext))]
    partial class PlutoRoverDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PlumGuide.Exercises.PlutoRover.DataAccess.Entities.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Position", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7add428f-6811-44f9-bbd8-be6b27fe907a"),
                            Direction = 78,
                            X = 0,
                            Y = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
